DFJoueurBundle_newEffectif:
    pattern:  /admin/joueurs/new-effectif/{id_club}/
    defaults: { _controller: DFJoueurBundle:Private:newEffectif }
    requirements:
        id_club: \d+

DFJoueurBundle_showJoueurAdmin:
    pattern: /admin/joueurs/show/
    defaults: { _controller: DFJoueurBundle:Private:showJoueur }
    
DFJoueurBundle_selectNewEffectif:
    pattern: /admin/select-effectif/
    defaults: { _controller: DFJoueurBundle:Private:selectNewEffectif }
    
    
DFJoueurBundle_showProTeamEffectif:
    pattern: /equipe-pro/effectif/
    defaults: { _controller: DFJoueurBundle:Public:showProTeamEffectif }
    
DFJoueurBundle_showJoueur: 
    pattern: /joueur/{nom}-{prenom}-{joueur_id}/
    defaults: { _controller: DFJoueurBundle:Public:showJoueur }